name: Build and release container

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
      - LICENCE
      - TRANSLATION
      - invidious.service
      - .git*
      - .editorconfig

      - screenshots/*
      - .github/ISSUE_TEMPLATE/*
      - kubernetes/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.6.0
        with:
          crystal: 1.5.0

      - name: Run lint
        run: |
          if ! crystal tool format --check; then
            crystal tool format
            git diff
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker AMD64 image without QUIC for Push Event
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            braunbearded/invidious:latest
            braunbearded/invidious:${{ github.sha }}
          build-args: |
            "release=1"
            "disable_quic=1"

      - name: Build and push Docker ARM64 image without QUIC for Push Event
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.arm64
          platforms: linux/arm64/v8
          push: true
          tags: |
            braunbearded/invidious:latest-arm64
            braunbearded/invidious:${{ github.sha }}-arm64
          build-args: |
            "release=1"
            "disable_quic=1"
        
      - name: Build and push Docker AMD64 image with QUIC for Push Event
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            braunbearded/invidious:latest-quic
            braunbearded/invidious:${{ github.sha }}-quic
          build-args: release=1

      - name: Build and push Docker ARM64 image with QUIC for Push Event
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.arm64
          platforms: linux/arm64/v8
          push: true
          tags: |
            braunbearded/invidious:latest-arm64-quic
            braunbearded/invidious:${{ github.sha }}-arm64-quic
          build-args: release=1
